# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52b2c05419fc3998e3a15e20eb2f5286"
name = "Dev Ajmera Form Manager "
application_url = "https://lodge-its-bidding-slight.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://lodge-its-bidding-slight.trycloudflare.com/api/auth" ]

[app_proxy]
url = "https://lodge-its-bidding-slight.trycloudflare.com"
subpath = "devAjmeraTyres"
prefix = "apps"

